name: test_local_noti

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  timezone: ^0.9.4
  cupertino_icons: ^1.0.8
  flutter_timezone: ^3.0.1
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  android: true
  min_sdk_android: 21
  image_path: "assets/images/launcher.png"
  web:
    generate: true
    image_path: "assets/images/launcher.png"
  windows:
    generate: true
    image_path: "assets/images/launcher.png"
  macos:
    generate: true
    image_path: "assets/images/launcher.png"
